# Available command prefixes. 
# Any message that starts with these characters will be interpreted as a command.
prefixes:
  - '.'
  - '!'
messages:
  # Maximum allowed length of the tag list before being cut off.
  max_tag_length: 512

  # Maximum allowed length of the image description before being cut off.
  max_desc_length: 256
# Derpibooru-specific configuration.
booru:
  # Base URL for API calls.
  api_url: "https://derpibooru.org"

  # Derpibooru API key to use.
  api_key: ''

  # Filter to use in NSFW channels.
  nsfw_filter: 56027

  # Filter to use in SFW channels.
  sfw_filter: 100073

  # Tags to hide, separated by adapter.
  hidden_tags:
    discord:
      # Arrays are considered as AND conditions.
      # Use leading ! to indicate NOT.
      - [ grimdark, torture ]
      - [ grimdark, animal abuse]
      - [ gore, grotesque ]
      - [ foalcon, '!safe' ]
      - kill yourself
    irc:
# Any bots not defined here will not be created.
bots:
  bot_id:
    token: 'secret_token'
    type: discord
